#!/bin/bash
echo "Starting Darknet via bash command"
cd vision/darknet
./darknet detector demo cfg/coco.data cfg/yolo.cfg yolo.weights &
echo "Waiting for Darknet to init"
sleep 6
echo "Start fusion algorithm"
cd ../..
python fusion/fusion.py
